CREATE DATABASE RKdigitalsDB

USE RKdigitalsDB

CREATE TABLE USERS
(
	ID INT PRIMARY KEY IDENTITY(2000,1),
	FULLNAME VARCHAR(MAX),
	USERNAME VARCHAR(MAX),
	EMAIL VARCHAR(MAX),
	MOBILENUMBER BIGINT,
	PASSWORDHASH VARBINARY(MAX),
	PASSWORDKEY VARBINARY(MAX),
	TOKEN VARCHAR(MAX),
	ROLE VARCHAR(MAX)
)

CREATE TABLE PRODUCTS
(
	ID INT PRIMARY KEY IDENTITY(2000,1),
	PRODUCTNAME VARCHAR(MAX),
	PRODUCTDESCRIPTION VARCHAR(MAX),
	PRODUCTPRICE INT,
	PRODUCTIMAGE VARCHAR(MAX),
)

CREATE TABLE CART
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	ProductId INT FOREIGN KEY REFERENCES PRODUCTS(ID),
	UserId INT FOREIGN KEY REFERENCES USERS(ID),
	Quntity INT
)


SELECT c.ID as CartID,c.Quntity,p.PRODUCTNAME,p.PRODUCTIMAGE,
	   p.PRODUCTDESCRIPTION,p.PRODUCTPRICE,
	   u.USERNAME,
	   u.ID as UserID
	   FROM CART as c
inner join PRODUCTS as p on c.ProductId =p.ID
inner join USERS as u on c.UserId =u.ID where c.UserId=2000

SELECT * FROM USERS
SELECT * FROM PRODUCTS
SELECT * FROM CART

insert into PRODUCTS values('Brown Table Photo Frame'
				            ,'1 Photo Frame,Golden Peacock,Engineered wood',
							200,'image'
)
update USERS set Role='seller' where Fullname='rk';